### ISSUE TITLE
Some cucumber test files run via several CI jobs

### ISSUE THREAD

**Issue by Hirurg103** [ArturT/knapsack#91]
System configuration:

**rails**: 5.2.0
**cucumber**: 3.1.2
**cucumber-rails**: 1.6.0
**knapsack**: 1.17.1

I am running my cucumber features on Gitlab CI with knapsack. I noticed that some cucumber features are running via several CI jobs and in the result they are running two or more times.

I set `CI_NODE_INDEX` and `CI_NODE_TOTAL` in the before script

```yaml
before_script:
  # Prepare knapsack env and metadata
  - export JOB_NAME=( $CI_JOB_NAME )
  - export TEST_TOOL=${JOB_NAME[0]}
  - export CI_NODE_INDEX=${JOB_NAME[1]}
  - export CI_NODE_TOTAL=${JOB_NAME[2]}
  - echo "Finished configuration for $TEST_TOOL tests with knapsack for CI_NODE_INDEX=$CI_NODE_INDEX and CI_NODE_TOTAL=$CI_NODE_TOTAL"

.cucumber: &cucumber
  script:
    - echo "Starting cucumber tests with knapsack for CI_NODE_INDEX=$CI_NODE_INDEX and CI_NODE_TOTAL=$CI_NODE_TOTAL"
    - 'bundle exec rake "knapsack:cucumber[--p rerun -b]" || (echo "Re-run failed scenarios: `cat rerun.txt`" && bundle exec cucumber @rerun.txt)'

cucumber 0 13: *cucumber
cucumber 1 13: *cucumber
cucumber 2 13: *cucumber
...
cucumber 12 13: *cucumber
```

In out Gitlab CI job I see the following output:

![Screen Shot 2019-08-01 at 11 35 13 AM](https://user-images.githubusercontent.com/2171773/62278292-6f590880-b450-11e9-862c-fba96c3e32df.png)

and everything seems to be configured good.

But when I copied all the report features from `Report features:` output from knapsack and saved them into a file `cucumber_features_on_ci.txt` and checked this file for duplicated rows with

```ruby
File.readlines('cucumber_features_on_ci.txt').group_by(&:itself).select { |k, v| v.size > 1 }.size
=> 18
```

I noticed that there are duplicated feature files in this list

Also when I counted all the uniq lines in `cucumber_features_on_ci.txt` with

```ruby
features_on_ci = File.readlines('cucumber_features_on_ci.txt').map(&:strip).uniq.count
(features_on_ci - JSON.parse(File.read('knapsack_cucumber_report.json')).keys).size
=> 10
```
I noticed that there are less features than in my `knapsack_cucumber_report.json`

But when I run cucumber features with knapsack locally

```bash
CI_NODE_INDEX=0 CI_NODE_TOTAL=13 bundle exec rake "knapsack:cucumber[--p rerun -b]" || (echo "Re-run failed scenarios: `cat rerun.txt`" && bundle exec cucumber @rerun.txt)
...
CI_NODE_INDEX=12 CI_NODE_TOTAL=13 ...
```

and save output in `Report features:` to `cucumber_features_local.txt` there are no duplicated files:

```ruby
File.readlines('cucumber_features_local.txt').group_by(&:itself).select { |k, v| v.size > 1 }.size
=> 0
```
