### ISSUE TITLE
Knapsack report not found by one job on GitLab CI

### ISSUE THREAD

**Issue by erikthered** [ArturT/knapsack#94]
I'm having a weird issue where one job on GitLab CI throws the error `Knapsack report file knapsack_rspec_report.json doesn't exist. Please generate report first!`. The other jobs execute fine. I've tried regenerating the report as well as changing the parallel value (have tried 6 and 8), but the issue still persists.

I'm using knapsack (non-pro) 1.18.0, along with Ruby 2.3, Rails 3 and RSpec 3.5.0.

Any pointers on how to debug this issue?

**Comment by ArturT** [comment]
Do you have `knapsack_rspec_report.json` committed into your repo?

What is the knapsack command to run tests defined in GitLab CI yaml config?
Can you share the GitLab CI config?

BTW How long it takes to run your tests now?

**Comment by erikthered** [comment]
Yes, I have the json report committed. The command I'm using is `bundle exec rake "knapsack:rspec[--tag ~flaky --tag ~broken]"`. The full suite takes about 120 minutes in serial, but split on GitLab CI it's about 20-25 minutes per job.

I'll obfuscate some of the company specific details in the GitLab yaml and share in a follow-up comment.

**Comment by erikthered** [comment]
```
image: "ruby:2.3"

services:
  - mongo
  - mysql

variables:
  RAILS_ENV: "test"
  DB_HOST: "mysql"
  MYSQL_DATABASE: "test"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  TZ: US/Pacific

cache:
  paths:
    - vendor/bundle

before_script:
  - ruby -v # Print out ruby version for debugging
  - apt-get update -q && apt-get install mysql-client nodejs -yqq
  - mkdir $HOME/tmp
  - bundle install --local --path vendor/bundle
  - bundle exec rake db:structure:load
  - bundle env

rspec:
  script: bundle exec rake "knapsack:rspec[--tag ~feature --tag ~rtpos]"
  parallel: 6
  artifacts:
    reports:
      junit: rspec.xml
    paths:
      - rspec.xml
      - failures/
    when: always
```
